### ISSUE TITLE
Unexpected Textbox widget autosize when file has tabulations

### ISSUE THREAD

**Issue by mchubby** [frougon/pythondialog#1]
Hello,

When Dialog is created with `autowidgetsize=True`, the textbox widget does not size correctly if file contains Tab characters.

It is probably a dialog backend upstream issue (using 1.3-20160209 here), because passing "--textbox filename 0 0" gives this same result.

I worked around this behavior by computing dimensions using `maxsize()` so that window covers whole terminal regardless, but it's not an ideal situation.

**Comment by frougon** [comment]
Hello,

mchubby notifications@github.com wrote:

> Hello,
> 
> When Dialog is created with `autowidgetsize=True`, the textbox widget does not
> size correctly if file contains Tab characters.

Tab characters are evil. ;-)

> It is probably a dialog backend upstream issue (using 1.3-20160209 here),
> because passing "--textbox filename 0 0" gives this same result.

Indeed, this makes it sound like a dialog issue. In this case, your best
bet to get the problem fixed would be to contact the dialog maintainer,
Thomas E. Dickey. You can find his address at the bottom of:

  http://invisible-island.net/dialog/dialog.html

Regards

## 

Florent
