### ISSUE TITLE
Drop down menu, checkboxes and hidden content

### ISSUE THREAD

**Issue by GuazP** [frougon/pythondialog#13]
Is it possible to create following elements inside of pythondialog boxes?
- Drop down menu
- Hidden content
- Checkboxes

I attach screenshot of what I would like to see, however I didn't found it in documentation.
![pythondialog](https://user-images.githubusercontent.com/33330881/162724910-b006bfc6-ff3b-4250-84ee-7fef4d05bca1.png)
.

**Comment by frougon** [comment]
Hello,

There are `menu`, `checklist` and `passwordbox` widgets, but no way to have a dialog with mixed-contents like that, AFAICT (see the [screenshots gallery](https://pythondialog.sourceforge.io/gallery.html) for available widgets).

`pythondialog` is only an interface to [dialog](https://invisible-island.net/dialog/dialog.html). What  `dialog` can't do, `pythondialog` can't either (as far as GUI features are concerned).

Regards
