### ISSUE TITLE
best practice for unittesting?

### ISSUE THREAD

**Issue by Sispheor** [frougon/pythondialog#2]
Hi, thanks for your lib.

I don't find any doc about testing. Is that possible? If yes, what is the best practice? 
Thank you !

[Here is the class I would like to test](https://github.com/kalliope-project/kalliope/blob/master/kalliope/core/ShellGui.py) for giving you an idea if it can help.

**Comment by frougon** [comment]
Hi Nicolas,

I'm not sure it's very helpful, but I'd try with libs that allow faking keystrokes. I have good experience with [python-evdev](https://python-evdev.readthedocs.io/en/latest/) for faking mouse clicks, and apparently it can work with keyboards too. You may have to adjust the permissions of /dev/uinput, though...

Regards

**Comment by Sispheor** [comment]
Ok. I'll give a try. Thanks.
