### ISSUE TITLE
Wrong documentation for mixedform

### ISSUE THREAD

**Issue by tipok** [frougon/pythondialog#3]
The documentation has a wrong assignment for attributes in elements description

it says:
0 := hidden
1 := read only

but should be:
0 := text
1 := hidden
2 := read only

**Comment by frougon** [comment]
The documentation is correct. Please read the full sentence: “attributes is an integer interpreted as a bit mask with the following meaning (bit 0 being the least significant bit)”.

You have to understand binary notation and “bit mask”, of course. The 0 and 1 in the table following the quoted sentence are correctly referred to as being the "bit number" (in the bitmask), not the argument value. Setting bit 0 only gives the value 1; setting bit 1 only gives the value 2; setting both bits 0 and 1 gives the value 1 + 2 = 3 (11 in binary notation).

**Comment by frougon** [comment]
(and setting neither bit 0 nor 1 gives the value 0, of course: what you called "text")
