### ISSUE TITLE
Additional examples

### ISSUE THREAD

**Issue by cynthia-rempel** [frougon/pythondialog#5]
Hi,
I was playing with your code, and was wanting to offer some additional examples:
``
#! /usr/bin/env python3
import locale
from dialog import Dialog
``
''' This is almost always a good thing to do at the beginning of your programs. '''
locale.setlocale(locale.LC_ALL, '')
''' You may want to use 'autowidgetsize=True' here (requires pythondialog >= 3.1) '''
d = Dialog(dialog="dialog")
''' Dialog.set_background_title() requires pythondialog 2.13 or later '''
d.set_background_title("YES/NO Help sample")
''' In pythondialog 3.x, you can compare the return code to d.OK, Dialog.OK or
"ok" (same object). In pythondialog 2.x, you have to use d.DIALOG_OK, which
is deprecated since version 3.0.0.'''
user_selection = d.yesno("Hi, this is a yes/no dialog box. You can use this to ask\
 questions that have an answer of either yes or no.\
 BTW, do you notice that long lines will be automatically\
 wrapped around so that they can fit in the box? You can\
 also control line breaking explicitly by inserting\
 'backslash n' at any place you like, but in this case,\
 auto wrap around will be disabled and you will have to\
 control line breaking yourself.", title="YES/NO BOX",width=0,height=0,help_button=True)
if user_selection == d.OK:
    d.msgbox("You chose yes")
elif user_selection == d.CANCEL:
    d.msgbox("You chose no")
elif user_selection == d.HELP:
    d.msgbox("You pressed help")
elif user_selection == d.ESC:
    d.msgbox("You pressed ESC")
else:
    d.msgbox("WHAT DID YOU DO?!?!")

**Comment by cynthia-rempel** [comment]
``
#! /usr/bin/env python3

import locale
from dialog import Dialog

``# This is almost always a good thing to do at the beginning of your programs.
locale.setlocale(locale.LC_ALL, '')

``# You may want to use 'autowidgetsize=True' here (requires pythondialog >= 3.1)
d = Dialog(dialog="dialog")

``# Dialog.set_background_title() requires pythondialog 2.13 or later
d.set_background_title("YES/NO Extra sample")

``# In pythondialog 3.x, you can compare the return code to d.OK, Dialog.OK or

``# "ok" (same object). In pythondialog 2.x, you have to use d.DIALOG_OK, which

``# is deprecated since version 3.0.0.
user_selection = d.yesno("Hi, this is a yes/no dialog box. You can use this to ask\
 questions that have an answer of either yes or no.\
 BTW, do you notice that long lines will be automatically\
 wrapped around so that they can fit in the box? You can\
 also control line breaking explicitly by inserting\
 'backslash n' at any place you like, but in this case,\
 auto wrap around will be disabled and you will have to\
 control line breaking yourself.",
   title="YES/NO/MAYBE BOX",
   extra_label="Previous",
   ok_label="Next",
   width=0,
   height=0,
   extra_button=True)
if user_selection == d.OK:
    d.msgbox("You chose yes")
elif user_selection == d.CANCEL:
    d.msgbox("You chose no")
elif user_selection == d.HELP:
    d.msgbox("You pressed help")
elif user_selection == d.ESC:
    d.msgbox("You pressed ESC")
else:
    d.msgbox("WHAT DID YOU DO?!?!")

**Comment by frougon** [comment]
Hello,

I'm afraid formatting is completely broken in your messages... An easy way to insert a code fragment here  is to paste it into the text box, select it and click the <> button above the text box. This normally adds three backquotes above and below what you selected. Please click on _Preview_ to check the result before posting.

Concerning your suggestion, you are presumably referring to <http://pythondialog.sourceforge.net/>. I don't want to make this example longer than it is, but there are two other sample scripts shipped in the pythondialog distribution. These are [examples/simple_example.py](https://github.com/frougon/pythondialog/blob/master/examples/simple_example.py) and [examples/demo.py](https://github.com/frougon/pythondialog/blob/master/examples/demo.py). The kind of change you want to make would belong to simple_example.py, IMHO. If you send a clean patch or merge request about it, I'll be happy to merge it.

Regards

**Comment by frougon** [comment]
More than one year has passed without usable code, closing.
