### ISSUE TITLE
python3-dialog - no '*' character echo when entering the passwords in all the password dialogs

### ISSUE THREAD

**Issue by JoeKuan-itrinegy** [frougon/pythondialog#6]
I am currently using python3-dialog 3.4.0-1 (with Ubuntu 18.04). None of the password dialogs show the '*' characters when I enter the password but the dialog do record the password input.

Many thanks
Joe

**Comment by frougon** [comment]
Hello,

pythondialog is only a front-end to for dialog(1). Can you provide a dialog command line that shows the stars you would like to see?

**Comment by JoeKuan-itrinegy** [comment]
Found it. It is the '--insecure'  that makes the keypress echos.

```
dialog --title "Password" \
--clear --insecure \
--passwordbox "Enter your password" 10 30
```

**Comment by frougon** [comment]
Okay, I had forgotten that this option existed. You should be able to pass it to your dialog widget using a keyword argument (`insecure=True`) as explained [here](http://pythondialog.sourceforge.net/doc/Dialog_class_overview.html#passing-dialog-common-options). You might also be interested in [Dialog.add_persistent_args()](http://pythondialog.sourceforge.net/doc/Dialog_class_overview.html#dialog.Dialog.add_persistent_args), though I'd probably prefer something specific here.

**Comment by frougon** [comment]
I confirm that what I proposed in the previous message works, it is even in the pythondialog [demo.py](https://github.com/frougon/pythondialog/blob/master/examples/demo.py) (see MyApp.passwordbox_demo(), currently at line 1276):

```
def passwordbox_demo(self):
        # 'insecure' keyword argument only asks dialog to echo asterisks when
        # the user types characters. Not *that* bad.
        code, password = d.passwordbox("What is your root password, "
                                       "so that I can crack your system "
                                       "right now?", insecure=True)
return password
```
Hence, closing the report.
